name: "[Schedule] Remove old files"

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  delete_files:
    runs-on: ubuntu-latest
    name: Delete old files
    steps:
      - uses: actions/checkout@master
      - uses: daniL16/action-clean-old-files@master
        with:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          dir: './api/migrations'
          base_branch: 'master'
          days_old: '15'